### ISSUE TITLE
Does this work with .png files?

### ISSUE THREAD

**Issue by stevemart** [IBM/MAX-Facial-Age-Estimator-Web-App#18]
I've tried a few PNG files and they seem to crap out:

CLI:

```bash
Steves-MacBook-Pro:Downloads stevemar$ curl -F "image=@test1.png" -X POST http://localhost:5000/model/predict 
{"message": "Internal Server Error"}
```

container logs:

```bash
ERROR:flask.app:Exception on /model/predict [POST]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/conda/lib/python3.6/site-packages/flask_restplus/api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/flask_restplus/marshalling.py", line 136, in wrapper
    resp = f(*args, **kwargs)
  File "/workspace/api/model.py", line 62, in post
    preds = self.model_wrapper.predict(stillimg)
  File "/workspace/core/backend.py", line 79, in predict
    detected = self.detector.detect_faces(input_img)
  File "/opt/conda/lib/python3.6/site-packages/mtcnn/mtcnn.py", line 405, in detect_faces
    result = stage(img, result[0], result[1])
  File "/opt/conda/lib/python3.6/site-packages/mtcnn/mtcnn.py", line 446, in __stage1
    out = self.__pnet.feed(img_y)
  File "/opt/conda/lib/python3.6/site-packages/mtcnn/network.py", line 108, in feed
    return self._feed(image)
  File "/opt/conda/lib/python3.6/site-packages/mtcnn/mtcnn.py", line 71, in _feed
    return self._session.run(['pnet/conv4-2/BiasAdd:0', 'pnet/prob1:0'], feed_dict={'pnet/input:0': image})
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 961, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 615, 615, 4) for Tensor 'pnet/input:0', which has shape '(?, ?, ?, 3)'
```

Note that is there is no support for PNG files I'd be happy to create a PR to update the README with all supported file types

**Comment by I-Hong** [comment]
Thanks @stevemart. The Web-app is to use webcam, i.e., video, as input for real-time estimation. The Aga Estimator model (https://github.com/IBM/MAX-Facial-Age-Estimator) works for png, or jpg format.

**Comment by stevemart** [comment]
@i-hong yes, my question is in regards to the model, not the web app. The camera worked fine. 

Any idea why in getting the errors? I've tried a few png files and they've all been unsuccessful

**Comment by I-Hong** [comment]
@stevemart, thanks for this. It worked well for png and jpg formats. I am not sure what the problem is yet.
